# Study numpy broadcasting

In [1]:
import numpy as np

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when
1. they are equal, or
2. one of them is 1

In [2]:
a = np.zeros((5, 3, 5))

In [7]:
print len(a)

2


In [3]:
print a
print a.shape

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]
(5L, 3L, 5L)


In [4]:
scale = np.arange(5)

In [5]:
print scale
print scale.shape

[0 1 2 3 4]
(5L,)


In [6]:
result = a + scale

In [7]:
print result

[[[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]]


In [8]:
print result[0, : ,:]

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [9]:
print result[1, :, :]

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [10]:
print result[:, 0, :]

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


# Study slicing

In [11]:
b = np.arange(75).reshape((5,3,5))

In [12]:
print b

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]


In [13]:
print b[0, :, :]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
print b[:, 1, :]

[[ 5  6  7  8  9]
 [20 21 22 23 24]
 [35 36 37 38 39]
 [50 51 52 53 54]
 [65 66 67 68 69]]


In [15]:
print b[:, :, 2]

[[ 2  7 12]
 [17 22 27]
 [32 37 42]
 [47 52 57]
 [62 67 72]]


In [16]:
print b[:, :, 2].shape

(5L, 3L)


# Refer to https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html for more information.

# Study np.where and np.argwhere

In [3]:
a = np.arange(9).reshape((3,3))

In [4]:
print a

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print a < 5

[[ True  True  True]
 [ True  True False]
 [False False False]]


In [6]:
print (a < 5).astype(np.int)

[[1 1 1]
 [1 1 0]
 [0 0 0]]


In [13]:
print np.where(a<5)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))


In [14]:
print (a<5).nonzero()

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))


In [15]:
print np.where(a<5, a, 0)

[[0 1 2]
 [3 4 0]
 [0 0 0]]


In [16]:
print np.where(a<5, a, False)

[[0 1 2]
 [3 4 0]
 [0 0 0]]


In [17]:
print np.argwhere(a<5)

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]]


# numpy help

In [18]:
np.array?

In [19]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new__
    Create a new masked array from scratch.
numpy.lib.ar

In [20]:
np.lookfor('create two-dim array')

Search results for 'create two-dim array'
-----------------------------------------
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fft.ifft
    Compute the one-dimensional inverse discrete Fourier Transform.
numpy.fft.ifftn
    Compute the N-dimensional inverse discrete Fourier Transform.


In [21]:
np.lookfor('create two dim array')

Search results for 'create two dim array'
-----------------------------------------
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.nditer
    Efficient multi-dimensional iterator object to iterate over arrays.
numpy.histogram2d
    Compute the bi-dimensional histogram of two data samples.
numpy.lib.arrayterator.Arrayterator
    Buffered iterator for big arrays.
numpy.ndarray
    ndarray(shape, dtype=float, buffer=None, offset=0,
numpy.fft.ifft
    Compute the one-dimensional inverse discrete Fourier Transform.
numpy.fft.ifftn
    Compute the N-dimensional inverse discrete Fourier Transform.
numpy.diagonal
    Return specified diagonals.

In [22]:
np.arr*?