# This notebook is used to implement numerical differenciation

In [1]:
import numpy as np

In [2]:
def f(x):
    # x: ndarray obj
    # y is a scaler, and is the output.
    x = np.array(x)
    y = np.sum(x ** 2) / 2
    return y

In this notebook, we are going to compute the numerical differencation of the functon $f(x) = 0.5\cdot(x^2_1 + x^2_2 + x^2_3)$

In [3]:
x = range(3)

In [4]:
print(f(x))

2.5


## Compute numerically 

In [5]:
def df_numerical1(func, h, x0):
    # func: function name;
    # val_num: number of inputs of func;
    # h;
    # x0: 1-d ndarray obj
    # dy: gradient, 1-dim ndarray obj;
    x0 = np.array(x0)
    dy = np.zeros(x0.shape)
    for n in range(x0.size):
        # If I use x = np.copy, entry of 
        dx = np.zeros(x0.shape)
        dx[n] += h
        x = x0 + dx
        print('x={}, x0={}'.format(x, x0))
        dy[n] = (func(x) - func(x0)) / h
    return dy

In [6]:
dy1 = df_numerical1(f, 0.1, [0, 1, 2])

x=[0.1 1.  2. ], x0=[0 1 2]
x=[0.  1.1 2. ], x0=[0 1 2]
x=[0.  1.  2.1], x0=[0 1 2]


In [7]:
print(dy1)

[0.05 1.05 2.05]


In [8]:
dy1 = df_numerical1(f, 0.0001, [0, 1, 2])

x=[1.e-04 1.e+00 2.e+00], x0=[0 1 2]
x=[0.     1.0001 2.    ], x0=[0 1 2]
x=[0.     1.     2.0001], x0=[0 1 2]


In [9]:
print(dy1)

[4.99999997e-05 1.00005000e+00 2.00005000e+00]


## Another way to compute numerically

In [10]:
def df_numerical2(func, h, x0):
    # func: function name;
    # h:
    # x0: 
    # dy: output
    x0 = np.array(x0)
    dy = np.empty(x0.shape)
    for n in range(x0.size):
        dx = np.zeros(x0.shape)
        dx[n] = h
        print('dx = {}'.format(dx))
        dy[n] = (func(x0 + dx) - func(x0 - dx)) / (2 * h)
    return dy    

In [11]:
dy2 = df_numerical2(f, 0.1, [0, 1, 2])
print(dy2)

dx = [0.1 0.  0. ]
dx = [0.  0.1 0. ]
dx = [0.  0.  0.1]
[0. 1. 2.]


In [12]:
def grad_f(x0):
    # x0:
    # dy:
    x0 = np.array(x0)
    dy = np.empty(x0.shape)
    dy = x0
    return dy

In [13]:
dy_grad = grad_f([0, 1, 2])

In [14]:
print(dy_grad)

[0 1 2]
