# This notebook is used to implement numerical differenciation

In [1]:
import numpy as np

In [2]:
def f(x):
    # x: ndarray obj
    # y is a scaler, and is the output.
    x = np.array(x)
    y = np.sum(x ** 2) / 2
    return y

In this notebook, we are going to compute the numerical differencation of the functon $f(x) = 0.5\cdot(x^2_1 + x^2_2 + x^2_3)$

In [3]:
x = range(3)

In [4]:
print(f(x))

2.5


## Compute numerically 

In [5]:
def df_numerical1(func, h, x0):
    # func: function name;
    # val_num: number of inputs of func;
    # h;
    # x0: 1-d ndarray obj
    # dy: gradient, 1-dim ndarray obj;
    x0 = np.array(x0)
    dy = np.zeros(x0.shape)
    for n in range(x0.size):
        # If I use x = np.copy, entry of 
        dx = np.zeros(x0.shape)
        dx[n] += h
        x = x0 + dx
        dy[n] = (func(x) - func(x0)) / h
    return dy

In [6]:
dy1 = df_numerical1(f, 0.1, [0, 1, 2])

In [7]:
print(dy1)

[0.05 1.05 2.05]


In [8]:
dy1 = df_numerical1(f, 0.0001, [0, 1, 2])

In [9]:
print(dy1)

[4.99999997e-05 1.00005000e+00 2.00005000e+00]


## Another way to compute numerically

In [10]:
def df_numerical2(func, h, x0):
    # func: function name;
    # h:
    # x0: 
    # dy: output
    x0 = np.array(x0)
    dy = np.empty(x0.shape)
    for n in range(x0.size):
        dx = np.zeros(x0.shape)
        dx[n] = h
        dy[n] = (func(x0 + dx) - func(x0 - dx)) / (2 * h)
    return dy    

In [11]:
dy2 = df_numerical2(f, 0.1, [0, 1, 2])
print(dy2)

[0. 1. 2.]


In [12]:
def grad_f(x0):
    # x0:
    # dy:
    x0 = np.array(x0)
    dy = x0
    return dy

In [13]:
dy_grad = grad_f([0, 1, 2])

In [14]:
print(dy_grad)

[0 1 2]


In [15]:
import time

In [16]:
N = 400
T = 100
x0 = np.random.randint(100, size=400)
print(x0)

[36  6 73 54 56 86 66 82 63 76 67 47 81 28 83 64 11 17 48 88  3 55  5 68
 52 51 14 53 43 49  5 36 61 36  8 20 39 92 59 53 20 77 69 57 47 77 64 50
 53 35 47 71 95 74 25 70 66 25  7 82 27 75 58 46 35 12 18 53 72 37 23 68
  9 73 95  5 87 80 13 61 26 83 51 67 74 54 28 32 74 66 83 97 71 36 78 41
 57 21 97 45 83 18 86 61 31 58 10 43 55 31 90 24 84 64 25 72 20 45 83 79
  8 50 89 37 94  8 69 25 79  2 23 76 55 76 32 59 28 19 96 73 27 45 68 18
  3 92 99 93 82 46 17  5 98 38 91 73 59 64 32 54 12 60 31  9 52 21  1  9
 12 29 48 84 42 24 48 33 92 36 61 87 33 37 86 31 59 83 32 40 61  3 97 37
 87 40 66  8 57 14 22 38 51 31 85 43 52 73 55 45 28 68  2 44 98 67 51 22
 93 48 80 60 55 28  4 98  1 32 90 33 69  2 57 24 90 54 89 67 87 11 91 28
 61 29 29 22 28  7 41 62 53  8 87  2 73 27 64 16 95 56 87 29 59  2 19 93
 69  1 78 14 45 96 85 78  0 45 29 85 36  2 19 43 70 67 39 25 79 44 79 26
 13 63  8  8  9 79 69 48 91 41 63 29  5 90 24 44 20 80  2 97 10 49 17 40
 24 25 23 29 96  2 33 20 50 23  7  6 17 16 53 51 48

In [17]:
timein = time.time()
for t in range(T):
    dy1 = df_numerical1(f, 0.001, x0)
timeout = time.time()
time1 = timeout - timein
print(time1)

1.2567002773284912


In [18]:
timein = time.time()
for t in range(T):
    dy2 = df_numerical2(f, 0.001, x0)
timeout = time.time()
time2 = timeout - timein
print(time2)

1.5223445892333984


In [19]:
timein = time.time()
for t in range(T):
    dy = grad_f(x0)
timeout = time.time()
time = timeout - timein
print(time)

0.004777669906616211


In [20]:
compute_rate1 = time1 / time
print(compute_rate1)

263.0362293527621


In [21]:
compute_rate2 = time2 / time
print(compute_rate2)

318.6374569589301


In [25]:
def compute_rate_by_dimension():
    import time
    compute_rate1 = []
    compute_rate2 = []
    for n in range(100, 10001, 100):
        x0 = np.random.randint(n, size=n)
        time_in = time.time()
        for t in range(100):
            dy1 = df_numerical1(f, 0.001, x0)
        time_mid1 = time.time()
        for t in range(100):
            dy2 = df_numerical2(f, 0.001, x0)
        time_mid2 = time.time()
        for t in range(100):
            dy = grad_f(x0)
        time_out = time.time()
    time1 = time_mid1 - time_in
    time2 = time_mid2 - time_mid1
    time_grad = time_out - time_mid2
    compute_rate1.append(time1 / time_grad)
    compute_rate2.append(time2 / time_grad)
    return compute_rate1. compute_rate2

In [ ]:
compute_r1, compute_r2 = compute_rate_by_dimension()