# This notebook is used to implement numerical differenciation

In [2]:
import numpy as np

In [3]:
def f(x):
    # x: ndarray obj
    # y is a scaler, and is the output.
    x = np.array(x)
    y = np.sum(x ** 2) / 2
    return y

In this notebook, we are going to compute the numerical differencation of the functon $f(x) = 0.5\cdot(x^2_1 + x^2_2 + x^2_3)$

In [4]:
x = range(3)

In [5]:
print(f(x))

2.5


## Computer numerically

In [10]:
def df_numerical1(func, h, x0):
    # func: function name;
    # val_num: number of inputs of func;
    # h;
    # x0: 1-d ndarray obj
    # dy: gradient, 1-dim ndarray obj;
    x0 = np.array(x0)
    dy = np.zeros(x0.shape)
    for n in range(x0.size):
        # If I use x = np.copy, entry of 
        dx = np.zeros(x0.shape)
        dx[n] += h
        x = x0 + dx
        print('x={}, x0={}'.format(x, x0))
        dy[n] = (func(x) - func(x0)) / h
    return dy

In [11]:
dy = df_numerical1(f, 0.1, [0, 1, 2])

x=[0.1 1.  2. ], x0=[0 1 2]
x=[0.  1.1 2. ], x0=[0 1 2]
x=[0.  1.  2.1], x0=[0 1 2]


In [9]:
print(dy)

[0.05 1.05 2.05]


In [45]:
dy = df_numerical1(f, 3, 0.0001, [0, 1, 2])

In [46]:
print(dy)

[4.99999997e-05 1.00005000e+00 2.00005000e+00]


In [48]:
def grad_f(x0):
    # x0:
    # dy:
    x0 = np.array(x0)
    dy = np.empty(x0.shape)
    dy = 2 * x0
    return dy

In [50]:
dy2 = grad_f([0, 1, 2])

In [51]:
print(dy2)

[0. 2. 4.]
