# This notebook is used to implement numerical differenciation

In [1]:
import numpy as np

In [2]:
def f(x):
    # x: ndarray obj
    # y is a scaler, and is the output.
    x = np.array(x)
    y = np.sum(x ** 2) / 2
    return y

In this notebook, we are going to compute the numerical differencation of the functon $f(x) = 0.5*(x^2_1 + x^2_2 + x^2_3)$

In [3]:
x = range(3)

In [4]:
print(f(x))

2.5


## Computer numerically

In [42]:
def df_numerical1(func, val_num, h, x0):
    # func: function name;
    # val_num: number of inputs of func;
    # h;
    # x0: 1-d ndarray obj
    # dy: gradient, 1-dim ndarray obj;
    x0 = np.array(x0)
    dy = np.empty(val_num)
    for n in range(val_num):
        # If I use x = np.copy, entry of 
        x = np.zeros(val_num)
        x = x + x0
        x[n] = x0[n] + h
        dy[n] = (func(x) - func(x0)) / h
    return dy

In [43]:
dy = df_numerical1(f, 3, 0.1, [0, 1, 2])

In [44]:
print(dy)

[0.05 1.05 2.05]


In [45]:
dy = df_numerical1(f, 3, 0.0001, [0, 1, 2])

In [46]:
print(dy)

[4.99999997e-05 1.00005000e+00 2.00005000e+00]


In [48]:
def grad_f(x0):
    # x0:
    # dy:
    x0 = np.array(x0)
    dy = np.empty(x0.shape)
    for n in range(dy.size):
        dy[n] = 2 * x0[n]
    return dy

In [50]:
dy2 = grad_f([0, 1, 2])

In [51]:
print(dy2)

[0. 2. 4.]
