# Study numpy broadcasting

In [2]:
import numpy as np

In [2]:
a = np.zeros((5, 3, 5))

In [3]:
print a

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [4]:
scale = np.arange(5)

In [5]:
print scale

[0 1 2 3 4]


In [12]:
result = a + scale

In [13]:
print result

[[[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  1.  2.  3.  4.]]]


In [14]:
print result[0, : ,:]

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [15]:
print result[1, :, :]

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [16]:
print result[:, 0, :]

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


# Study slices

In [17]:
b = np.arange(75).reshape((5,3,5))

In [18]:
print b

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]]


In [19]:
print b[0, :, :]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
print b[:, 1, :]

[[ 5  6  7  8  9]
 [20 21 22 23 24]
 [35 36 37 38 39]
 [50 51 52 53 54]
 [65 66 67 68 69]]


In [21]:
print b[:, :, 2]

[[ 2  7 12]
 [17 22 27]
 [32 37 42]
 [47 52 57]
 [62 67 72]]


In [22]:
print b[:, :, 2].shape

(5L, 3L)


# Study np.where and np.argwhere

In [3]:
a = np.arange(9).reshape((3,3))

In [4]:
print a

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print np.where(a<5)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))


In [7]:
print (a<5).nonzero()

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))


In [8]:
print np.where(a<5, a, 0)

[[0 1 2]
 [3 4 0]
 [0 0 0]]


In [12]:
print np.where(a<5, a, False)

[[0 1 2]
 [3 4 0]
 [0 0 0]]


In [9]:
print np.argwhere(a<5)

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]]


In [10]:
print a[np.argwhere(a<5)]

[[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [6 7 8]]

 [[3 4 5]
  [0 1 2]]

 [[3 4 5]
  [3 4 5]]]
